[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Justin Kwok"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2 = "^2.9"
boto3 = "^1.28.35"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
